CC = gcc
CFLAGS = -I./include/ `pkg-config --cflags openssl`
LDFLAGS = `pkg-config --libs openssl`
SRCS = \
	accesscontrol.c \
	ssl.c

OBJS = ${SRCS:.c=.o}

all: accesscontrol

accesscontrol: ${OBJS}
	${CC} -o $@ ${OBJS} ${LDFLAGS}

clean:
	rm -f *.o accesscontrol

test:
	./accesscontrol
