CC = gcc
CFLAGS = -I./include/
LDFLAGS = -lssl -lcrypto
SRCS = \
	accesscontrol.c \
	ssl.c

OBJS = ${SRCS:.c=.o}

all: accesscontrol

accesscontrol: ${OBJS}
	${CC} -o $@ ${OBJS} ${LDFLAGS}

clean:
	rm -f *.o accesscontrol

test:
	./accesscontrol
